### ISSUE TITLE
Connection closing during request

### ISSUE THREAD

**Issue by waghanza** [priviterag/teradata-cli#1]
Hi,

I use **teradata** for warehouse activities. I execute an extraction (for data analysis) and _teradata-cli_ show me this stack trace :

``` ruby
/usr/local/share/gems/gems/teradata-cli-0.0.4/lib/teradata-cli/connection.rb:998:in `[]=': index -6 out of string (IndexError)
    from /usr/local/share/gems/gems/teradata-cli-0.0.4/lib/teradata-cli/connection.rb:998:in `insert_fp'
    from /usr/local/share/gems/gems/teradata-cli-0.0.4/lib/teradata-cli/connection.rb:977:in `unmarshal'
    from /usr/local/share/gems/gems/teradata-cli-0.0.4/lib/teradata-cli/connection.rb:777:in `block in unmarshal'
    from /usr/local/share/gems/gems/teradata-cli-0.0.4/lib/teradata-cli/connection.rb:776:in `map'
    from /usr/local/share/gems/gems/teradata-cli-0.0.4/lib/teradata-cli/connection.rb:776:in `unmarshal'
    from /usr/local/share/gems/gems/teradata-cli-0.0.4/lib/teradata-cli/connection.rb:693:in `each_record'
    from hoovers/sql/terradata.rb:106:in `block (3 levels) in <main>'
    from /usr/local/share/gems/gems/teradata-cli-0.0.4/lib/teradata-cli/connection.rb:650:in `each_result_set'
    from hoovers/sql/terradata.rb:105:in `block (2 levels) in <main>'
    from /usr/local/share/gems/gems/teradata-cli-0.0.4/lib/teradata-cli/connection.rb:173:in `execute_query'
    from hoovers/sql/terradata.rb:104:in `block in <main>'
    from /usr/local/share/gems/gems/teradata-cli-0.0.4/lib/teradata-cli/connection.rb:68:in `initialize'
    from /usr/local/share/gems/gems/teradata-cli-0.0.4/lib/teradata-cli/connection.rb:36:in `new'
    from /usr/local/share/gems/gems/teradata-cli-0.0.4/lib/teradata-cli/connection.rb:36:in `connect'
    from hoovers/sql/terradata.rb:103:in `<main>'
```

Do you have an idea of what going on ?

Regards,

**Comment by priviterag** [comment]
Hi Marwan,Update to the latest version of the gem.Kind regards,Giuseppe                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone on the O2 network.                                                                                                                                                                                                                                        From: Marwan RabbâaSent: Thursday, 31 October 2013 16:22To: priviterag/teradata-cliReply To: priviterag/teradata-cliSubject: [teradata-cli] Connection closing during request (#1)Hi,

I use teradata for warehouse activities. I execute an extraction (for data analysis) and teradata-cli show me this stack trace :

/usr/local/share/gems/gems/teradata-cli-0.0.4/lib/teradata-cli/connection.rb:998:in `[]=': index -6 out of string (IndexError)
    from /usr/local/share/gems/gems/teradata-cli-0.0.4/lib/teradata-cli/connection.rb:998:in`insert_fp'
    from /usr/local/share/gems/gems/teradata-cli-0.0.4/lib/teradata-cli/connection.rb:977:in `unmarshal'
    from /usr/local/share/gems/gems/teradata-cli-0.0.4/lib/teradata-cli/connection.rb:777:in`block in unmarshal'
    from /usr/local/share/gems/gems/teradata-cli-0.0.4/lib/teradata-cli/connection.rb:776:in `map'
    from /usr/local/share/gems/gems/teradata-cli-0.0.4/lib/teradata-cli/connection.rb:776:in`unmarshal'
    from /usr/local/share/gems/gems/teradata-cli-0.0.4/lib/teradata-cli/connection.rb:693:in `each_record'
    from hoovers/sql/terradata.rb:106:in`block (3 levels) in <main>'
    from /usr/local/share/gems/gems/teradata-cli-0.0.4/lib/teradata-cli/connection.rb:650:in `each_result_set'
    from hoovers/sql/terradata.rb:105:in`block (2 levels) in <main>'
    from /usr/local/share/gems/gems/teradata-cli-0.0.4/lib/teradata-cli/connection.rb:173:in `execute_query'
    from hoovers/sql/terradata.rb:104:in`block in <main>'
    from /usr/local/share/gems/gems/teradata-cli-0.0.4/lib/teradata-cli/connection.rb:68:in `initialize'
    from /usr/local/share/gems/gems/teradata-cli-0.0.4/lib/teradata-cli/connection.rb:36:in`new'
    from /usr/local/share/gems/gems/teradata-cli-0.0.4/lib/teradata-cli/connection.rb:36:in `connect'
    from hoovers/sql/terradata.rb:103:in`<main>'

Do you have an idea of what going on ?

Regards,

—Reply to this email directly or view it on GitHub.

**Comment by waghanza** [comment]
thanks for quick reply
