### ISSUE TITLE
Teradata  Adapter for ActiveRecord

### ISSUE THREAD

**Issue by mohsensardari** [priviterag/teradata-cli#4]
Hi,
Are there any plans for adding a Teradata adapter for ActiveRecord? I'd like to contribute to build such an adapter and any feed-back is appreciated. Are there known roadblocks there?

**Comment by priviterag** [comment]
Hi,

I already started the ar adapter: https://github.com/priviterag/teradata-ar
It's partially working. I can't work on it since I have no Teradata access anymore.
